test get url

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -98,27 +98,27 @@ jobs:
             echo "Doing integration test with BRANCH=${CIRCLE_BRANCH} USERNAME=${CIRCLE_USERNAME}"
             MAIN_URL=$(node_modules/.bin/sls info --verbose | grep ServiceEndpoint: | cut -d ' ' -f2)
             echo "The links for testing: ${MAIN_URL}"
-            case "${CIRCLE_BRANCH}" in
-              master)
-                echo "Testing stage prod"
-                #INQUIRY_TABLE=Inquire-prod MESSAGE_TABLE=Message-prod REGION=us-east-1 pytest integration.py --stage=prod --url=${MAIN_URL}/inquiry
-              release/*)
-                echo "Testing stage qa"
-                #INQUIRY_TABLE=Inquire-qa MESSAGE_TABLE=Message-qa REGION=us-east-1 pytest integration.py --stage=qa --url=${MAIN_URL}/inquiry
-                ;;
-              develop)
-                echo "Testing stage dev"
-                #INQUIRY_TABLE=Inquire-dev MESSAGE_TABLE=Message-dev REGION=ap-southeast-1 pytest integration.py --stage=dev --url=${MAIN_URL}/inquiry
-                ;;
-              feature/*)
-                echo "Testing stage ${CIRCLE_USERNAME}"
-                #INQUIRY_TABLE=Inquire-${CIRCLE_USERNAME} MESSAGE_TABLE=Message-${CIRCLE_USERNAME} REGION=ap-southeast-1 pytest integration.py --stage=${CIRCLE_USERNAME} --url=${MAIN_URL}/inquiry
-                ;;
-              *)
-                echo "ERROR: unrecognized CIRCLE_BRANCH=${CIRCLE_BRANCH}"
-                exit 1
-                ;;
-            esac
+            #case "${CIRCLE_BRANCH}" in
+            #  master)
+            #    echo "Testing stage prod"
+            #    #INQUIRY_TABLE=Inquire-prod MESSAGE_TABLE=Message-prod REGION=us-east-1 pytest integration.py --stage=prod --url=${MAIN_URL}/inquiry
+            #  release/*)
+            #    echo "Testing stage qa"
+            #    #INQUIRY_TABLE=Inquire-qa MESSAGE_TABLE=Message-qa REGION=us-east-1 pytest integration.py --stage=qa --url=${MAIN_URL}/inquiry
+            #    ;;
+            #  develop)
+            #    echo "Testing stage dev"
+            #    #INQUIRY_TABLE=Inquire-dev MESSAGE_TABLE=Message-dev REGION=ap-southeast-1 pytest integration.py --stage=dev --url=${MAIN_URL}/inquiry
+            #    ;;
+            #  feature/*)
+            #    echo "Testing stage ${CIRCLE_USERNAME}"
+            #    #INQUIRY_TABLE=Inquire-${CIRCLE_USERNAME} MESSAGE_TABLE=Message-${CIRCLE_USERNAME} REGION=ap-southeast-1 pytest integration.py --stage=${CIRCLE_USERNAME} --url=${MAIN_URL}/inquiry
+            #    ;;
+            #  *)
+            #    echo "ERROR: unrecognized CIRCLE_BRANCH=${CIRCLE_BRANCH}"
+            #    exit 1
+            #    ;;
+            #esac
 workflows:
   version: 2
   pytest_slsdeploy:
